name       : libb2
version    : 0.98.1
release    : 1
source     :
    - https://github.com/BLAKE2/libb2/releases/download/v0.98.1/libb2-0.98.1.tar.gz : 53626fddce753c454a3fea581cbbc7fe9bbcf0bc70416d48fdbbf5d87ef6c72e
homepage   : https://www.blake2.net/
license    : CC0-1.0
component  : programming.library
summary    : BLAKE2 library implementation
description: |
    libb2 is a C library that provides support for BLAKE2b, BLAKE2s, BLAKE2bp and BLAKE2sp hashing.
setup      : |
    %configure \
        --disable-static \
        --enable-shared \
        --disable-native \
        --enable-fat
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
